FROM --platform=linux/arm64 public.ecr.aws/lambda/python:3.11

COPY requirements-lambda.txt .
RUN pip install --no-cache-dir -r requirements-lambda.txt

COPY src/ ${LAMBDA_TASK_ROOT}/src/
RUN chmod -R 755 src/

WORKDIR /var/task

CMD ["src.lambda_handler.lambda_handler"]
