# AUTO-GENERATED DRAFT — review before use
# Generated by: job-agent scraper generate https://www.experis.es/es/buscar-trabajo
# Confidence: 2 live endpoint(s) confirmed.

"""Experis Spain job scraper.

Experis Spain hosts their careers page at https://www.experis.es/es/buscar-trabajo
The site uses a React frontend with a backend API for job listings.

API endpoints:
  List:   POST https://www.experis.es/api/services/Jobs/searchjobs
          Body: {"filter":{"offset":0,"totalCount":0,"limit":10,
                 "searchkeyword":null,"haslocation":false,"language":"es"}}
          Paginates via "offset"; response's totalCount lives under
          "filters.totalCount", not top-level.

  Detail: GET  https://www.experis.es/es/oferta-de-empleo/{jobID}/{jobURL}
          Server-rendered (unlike the list page). Full job body is in a
          single div.details-rich-text container; the site doesn't
          structurally separate a "requirements" section from it.
"""

import logging
import re
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import requests
from bs4 import BeautifulSoup
from sqlalchemy.orm import Session

from src.job_scrapers.base_scraper import BaseScraper

logger = logging.getLogger("jobhunter.scrapers.experis")

LIST_URL = "https://www.experis.es/api/services/Jobs/searchjobs"
DETAIL_URL_TEMPLATE = "https://www.experis.es{job_url}"
APPLY_URL_TEMPLATE = "https://www.experis.es{job_url}"


class ExperisScraper(BaseScraper):
    """Scraper for Experis Spain career pages."""

    def __init__(self, session: Session):
        super().__init__(session)
        self._http = requests.Session()
        self._http.headers.update(
            {
                "Content-Type": "application/json",
                "Accept": "application/json",
                "User-Agent": (
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/120.0.0.0 Safari/537.36"
                ),
            }
        )

    def _get_source_name(self) -> str:
        return "experis"

    def _fetch_jobs(self, **kwargs: Any) -> List[Dict[str, Any]]:
        """Fetch all job listings from Experis Spain API.

        "offset" in this API's filter is a page number, not a record-skip
        index — offset=0/limit=50 returns records 0-49, but offset=1 returns
        the *next* 50 (records 50-99), not records 1-50. Incrementing it by
        `limit` each loop (record-offset semantics) skips straight past
        every valid page after the first and returns nothing thereafter,
        capping the result at one page. Confirmed against the live API by
        comparing job IDs returned at each offset.
        """
        all_jobs: List[Dict[str, Any]] = []
        page = 0
        limit = 50
        total_count = None

        while True:
            payload = {
                "filter": {
                    "offset": page,
                    "totalCount": total_count or 0,
                    "limit": limit,
                    "searchkeyword": None,
                    "haslocation": False,
                    "language": "es",
                }
            }

            try:
                resp = self._http.post(LIST_URL, json=payload, timeout=15)
                resp.raise_for_status()
            except requests.RequestException as e:
                logger.warning("Experis fetch error: %s", e)
                break

            data = resp.json()
            jobs = data.get("jobsItems", [])

            if not jobs:
                break

            all_jobs.extend(jobs)

            # totalCount is nested under "filters", not top-level.
            if total_count is None:
                total_count = data.get("filters", {}).get("totalCount", len(jobs))

            if len(all_jobs) >= total_count:
                break

            page += 1

            logger.info(
                "Fetched %d jobs (page=%d, total=%d)",
                len(jobs),
                page,
                total_count,
            )

        logger.info("Total jobs fetched: %d", len(all_jobs))
        return all_jobs

    def _parse_job(self, raw_job: Dict[str, Any]) -> Dict[str, Any]:
        """Parse a single job listing from Experis API response."""
        job_id = raw_job.get("jobID", "")
        job_url = raw_job.get("jobURL", "")
        job_title = raw_job.get("jobTitle", "")
        company_name = raw_job.get("companyName", "") or "Experis"
        job_location = raw_job.get("jobLocation", "")
        posted_date_str = raw_job.get("publishfromDate", "")

        posted_date = None
        if posted_date_str:
            try:
                # ISO 8601 format: 2026-08-26T08:40:54Z
                posted_date = datetime.fromisoformat(
                    posted_date_str.replace("Z", "+00:00")
                )
            except (ValueError, AttributeError):
                posted_date = datetime.now(timezone.utc)
        else:
            posted_date = datetime.now(timezone.utc)

        description = ""
        if job_url:
            detail_url = DETAIL_URL_TEMPLATE.format(job_url=job_url)
            description = self._fetch_job_description(detail_url)

        # Build apply URL
        apply_url = APPLY_URL_TEMPLATE.format(job_url=job_url) if job_url else ""

        return {
            "source_job_id": job_id,
            "title": job_title,
            # BaseScraper._create_job_object() reads "company" and
            # "posted_date" — the original draft used "company_name" and
            # "published_date", so every job would have saved with a null
            # company and null posted_date.
            "company": company_name,
            "location": job_location,
            "description": description,
            "requirements": None,  # not separately structured on this site
            "posted_date": posted_date,
            "apply_url": apply_url,
            "country": "es",  # Experis Spain is Spain-based
            "remote": self._infer_remote(description),
            "company_industry": "IT Staffing & Consulting",
            "company_size": "Large (>1,000)",
            "source_type": "company_portal",
        }

    def _fetch_job_description(self, detail_url: str) -> str:
        """Fetch the full job description from the job detail page.

        Unlike the search-results page (client-rendered, no data in static
        HTML), the detail page is server-rendered by Sitecore — the full job
        body is server-side in a single `div.details-rich-text` container
        (confirmed against a live listing). Generic class-name guessing
        (e.g. matching any class containing "description" or "content")
        was matching page-chrome elements — nav, search widgets — before
        ever reaching this one.
        """
        try:
            resp = self._http.get(detail_url, timeout=15)
            resp.raise_for_status()
        except requests.RequestException as e:
            logger.warning("Failed to fetch job details from %s: %s", detail_url, e)
            return ""

        try:
            soup = BeautifulSoup(resp.text, "html.parser")
            body = soup.find("div", class_="details-rich-text")
            return body.get_text(separator=" ", strip=True)[:5000] if body else ""
        except Exception as e:
            logger.warning("Error parsing job details: %s", e)
            return ""

    def _infer_remote(self, description: str) -> Optional[str]:
        """Infer "remote"/"onsite"/None from description text.

        Must return one of these literal strings, not a bool — the base
        class's Job.remote column and the matching engine (job_matcher.py,
        job_searcher.py) compare it against these exact strings. A bool
        silently stored as "1"/"0" text and matched neither.
        """
        if not description:
            return None

        description_lower = description.lower()

        # Check for remote indicators
        remote_keywords = [
            r"\bremoto\b",
            r"\bremote\b",
            r"100%\s*remoto",
            r"fully?\s+remote",
            r"work\s+from\s+home",
            r"teletrabajo",
        ]

        for keyword in remote_keywords:
            if re.search(keyword, description_lower):
                return "remote"

        # Check for on-site indicators
        onsite_keywords = [
            r"\bpresencial\b",
            r"on-?site",
            r"en nuestras oficinas",
            r"en la sede",
        ]

        for keyword in onsite_keywords:
            if re.search(keyword, description_lower):
                return "onsite"

        return None
