# AUTO-GENERATED DRAFT — review before use
# Generated by: job-agent scraper generate https://www.gibwork.com/
# Confidence: 2 live endpoint(s) confirmed.

"""GibWork job aggregator scraper.

GibWork is a job aggregator for Gibraltar. It provides a public JSON API at:

  Meta:  GET https://www.gibwork.com/meta.json
         Returns metadata about available jobs and sources.

  Jobs:  GET https://www.gibwork.com/jobs.json
         Returns a list of all jobs with abbreviated fields.

The API returns jobs from multiple ATS platforms and company portals.
Each job includes a title, company name, location, URL, and other metadata.
No authentication is required.
"""

import logging
from typing import Any, Dict, List

import requests
from sqlalchemy.orm import Session

from src.job_scrapers.base_scraper import BaseScraper

logger = logging.getLogger("jobhunter.scrapers.gibwork")

JOBS_API_URL = "https://www.gibwork.com/jobs.json"


class GibWorkScraper(BaseScraper):
    """Scraper for GibWork job aggregator."""

    def __init__(self, session: Session):
        super().__init__(session)
        self._http = requests.Session()
        self._http.headers.update(
            {
                "Accept": "application/json",
                "User-Agent": (
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/120.0.0.0 Safari/537.36"
                ),
            }
        )

    def _get_source_name(self) -> str:
        return "gibwork"

    def _fetch_jobs(self, **kwargs: Any) -> List[Dict[str, Any]]:
        """Fetch all jobs from GibWork API."""
        try:
            resp = self._http.get(JOBS_API_URL, timeout=15)
            resp.raise_for_status()
        except requests.RequestException as e:
            logger.warning("GibWork fetch error: %s", e)
            return []

        raw_jobs = resp.json()
        if not isinstance(raw_jobs, list):
            logger.warning("GibWork API returned unexpected format: %s", type(raw_jobs))
            return []

        logger.info("Fetched %d jobs from GibWork", len(raw_jobs))
        return raw_jobs

    def _parse_job(self, raw_job: Dict[str, Any]) -> Dict[str, Any]:
        """Parse GibWork job data into standardized format.

        Raw job fields from API:
            t: title
            u: apply_url
            s: company name
            st: source type (pri/gov/rec)
            c: category/department
            loc: location
            dom: domain
            ll: lat/long coordinates
            ats: ATS platform name
            logo: company logo URL
        """
        title = raw_job.get("t", "").strip()
        apply_url = raw_job.get("u", "").strip()
        company = raw_job.get("s", "").strip()
        location = raw_job.get("loc", "").strip()
        department = raw_job.get("c", "").strip()

        # Generate source_job_id from apply_url (stable across runs)
        # Fall back to a hash if URL is missing
        if apply_url:
            source_job_id = apply_url.split("/")[-1] or apply_url
        else:
            source_job_id = None

        # GibWork is a Gibraltar-only job board (every listing observed has
        # loc="Gibraltar") — set the country explicitly rather than relying on
        # base-class inference, since "Gibraltar" isn't in _infer_country()'s
        # residency pattern table and would otherwise always come back None.
        country = "gi"

        # GibWork itself is the aggregator for every job regardless of the
        # original employer type. The API's "st" field (pri/gov/rec) describes
        # whether the underlying poster is a private company, government body,
        # or recruiter — it says nothing about scrape provenance, so it must
        # not drive source_type (Job.source_type: did we scrape this directly
        # from the company's own careers site, or via a secondary aggregator).
        # Matches adzuna_scraper.py/themuse_scraper.py, which hardcode this too.
        source_type = "aggregator"

        # Remote status not available in API, leave as None
        remote = None

        parsed = {
            "source_job_id": source_job_id,
            "title": title,
            "company": company,
            "apply_url": apply_url,
            "location": location if location else None,
            "department": department if department else None,
            "country": country,
            "remote": remote,
            "source_type": source_type,
        }

        return parsed
